// Generated by CoffeeScript 1.4.0
var hideAllPopovers, hideAllPopoversExcept, showPopover;

$(document).keydown(function(e) {
  if (e.keyCode === 27) {
    return hideAllPopovers();
  }
});

hideAllPopovers = function() {
  return $('[rel="popover"]').popover('hide');
};

hideAllPopoversExcept = function(survivor) {
  return $('[rel="popover"]').not(survivor).popover('hide');
};

showPopover = function(el, title, content, placement) {
  el.find('[rel="popover"]').popover({
    placement: placement,
    trigger: 'manual',
    html: true,
    title: title,
    content: content
  }).click(function(evt) {
    evt.stopPropagation();
    hideAllPopoversExcept(this);
    return $(this).popover('toggle');
  });
  return $(document).click(function(e) {
    if ($(e.target).parents('[rel="popover"],.popover').length === 0) {
      return hideAllPopovers();
    }
  });
};
